language: node_js
node_js:
  - "8"
  - "node"
env:
  - NODE_ENV=test
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
before_script: greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn test
  - yarn build
after_script: greenkeeper-lockfile-upload
cache:
  yarn: true
  directories:
    - node_modules